[2023-12-14T18:20:26.984+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_fda.load manual__2023-12-14T18:19:43.986976+00:00 [queued]>
[2023-12-14T18:20:26.988+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_fda.load manual__2023-12-14T18:19:43.986976+00:00 [queued]>
[2023-12-14T18:20:26.989+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-14T18:20:26.995+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load> on 2023-12-14 18:19:43.986976+00:00
[2023-12-14T18:20:26.999+0000] {standard_task_runner.py:57} INFO - Started process 83 to run task
[2023-12-14T18:20:27.002+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'open_fda', 'load', 'manual__2023-12-14T18:19:43.986976+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/outcome_dag.py', '--cfg-path', '/tmp/tmpsets0158']
[2023-12-14T18:20:27.003+0000] {standard_task_runner.py:85} INFO - Job 5: Subtask load
[2023-12-14T18:20:27.033+0000] {task_command.py:416} INFO - Running <TaskInstance: open_fda.load manual__2023-12-14T18:19:43.986976+00:00 [running]> on host 3237edf0539d
[2023-12-14T18:20:27.070+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_fda' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-14T18:19:43.986976+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-14T18:19:43.986976+00:00'
[2023-12-14T18:20:27.072+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:314: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-12-14T18:36:01.091+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DependentObjectsStillExist: cannot drop table firm because other objects depend on it
HINT:  Use DROP ... CASCADE to drop the dependent objects too.


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/load.py", line 18, in load_data
    df_firm.to_sql('firm', engine, index=False,if_exists='replace')
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1910, in to_sql
    table = self.prep_table(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1814, in prep_table
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 907, in create
    self.pd_sql.drop_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1963, in drop_table
    self.get_table(table_name, schema).drop(bind=self.con)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/schema.py", line 979, in drop
    bind._run_ddl_visitor(ddl.SchemaDropper, self, checkfirst=checkfirst)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 1106, in visit_table
    self.connection.execute(DropTable(table))
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InternalError: (psycopg2.errors.DependentObjectsStillExist) cannot drop table firm because other objects depend on it
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE firm]
(Background on this error at: https://sqlalche.me/e/14/2j85)
[2023-12-14T18:36:01.130+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=open_fda, task_id=load, execution_date=20231214T181943, start_date=20231214T182026, end_date=20231214T183601
[2023-12-14T18:36:01.142+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 5 for task load ((psycopg2.errors.DependentObjectsStillExist) cannot drop table firm because other objects depend on it
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

[SQL: 
DROP TABLE firm]
(Background on this error at: https://sqlalche.me/e/14/2j85); 83)
[2023-12-14T18:36:01.178+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T18:36:01.194+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
