[2023-12-14T10:55:45.461+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T10:55:45.465+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T10:55:45.465+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-14T10:55:45.471+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-13 00:00:00+00:00
[2023-12-14T10:55:45.476+0000] {standard_task_runner.py:57} INFO - Started process 101 to run task
[2023-12-14T10:55:45.479+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'open_fda', 'transform', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/outcome_dag.py', '--cfg-path', '/tmp/tmp74u32byz']
[2023-12-14T10:55:45.481+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask transform
[2023-12-14T10:55:45.516+0000] {task_command.py:416} INFO - Running <TaskInstance: open_fda.transform scheduled__2023-12-13T00:00:00+00:00 [running]> on host e3645a97e7b5
[2023-12-14T10:55:45.562+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_fda' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2023-12-14T10:55:45.565+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/transformation.py", line 7, in transform_data
    create_table()
  File "/opt/airflow/dags/db/table_creation.py", line 14, in create_table
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5439" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

[2023-12-14T10:55:45.577+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=open_fda, task_id=transform, execution_date=20231213T000000, start_date=20231214T105545, end_date=20231214T105545
[2023-12-14T10:55:45.590+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task transform (connection to server on socket "/var/run/postgresql/.s.PGSQL.5439" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
; 101)
[2023-12-14T10:55:45.611+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T10:55:45.626+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-14T22:36:46.016+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T22:36:46.021+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T22:36:46.021+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-14T22:36:46.028+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-13 00:00:00+00:00
[2023-12-14T22:36:46.034+0000] {standard_task_runner.py:57} INFO - Started process 97 to run task
[2023-12-14T22:36:46.040+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'open_fda', 'transform', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/outcome_dag.py', '--cfg-path', '/tmp/tmpnzbz505w']
[2023-12-14T22:36:46.041+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask transform
[2023-12-14T22:36:46.136+0000] {task_command.py:416} INFO - Running <TaskInstance: open_fda.transform scheduled__2023-12-13T00:00:00+00:00 [running]> on host 3a11139d188c
[2023-12-14T22:36:46.257+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_fda' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2023-12-14T22:36:46.991+0000] {logging_mixin.py:154} INFO - Tables have been created
[2023-12-14T22:36:47.067+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:314: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-12-14T22:36:49.423+0000] {warnings.py:109} WARNING - /opt/***/dags/etl/transformation.py:61: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_values[f'{col}_id'] = range(max_id + 1, max_id + 1 + len(new_values))

[2023-12-14T22:36:52.376+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-13_recall_fct.csv'.
[2023-12-14T22:36:55.657+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-13_firm_dim.csv'.
[2023-12-14T22:36:56.283+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-13_status_dim.csv'.
[2023-12-14T22:36:56.786+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-13_cause_dim.csv'.
[2023-12-14T22:36:56.795+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-14T22:36:56.837+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=open_fda, task_id=transform, execution_date=20231213T000000, start_date=20231214T223646, end_date=20231214T223656
[2023-12-14T22:36:56.884+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-14T22:36:56.904+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
