[2023-12-14T10:55:46.826+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-14T10:55:46.837+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-14T10:55:46.840+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-14T10:55:46.852+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-12 00:00:00+00:00
[2023-12-14T10:55:46.857+0000] {standard_task_runner.py:57} INFO - Started process 108 to run task
[2023-12-14T10:55:46.863+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'open_fda', 'transform', 'scheduled__2023-12-12T00:00:00+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/outcome_dag.py', '--cfg-path', '/tmp/tmpko568rie']
[2023-12-14T10:55:46.864+0000] {standard_task_runner.py:85} INFO - Job 8: Subtask transform
[2023-12-14T10:55:46.924+0000] {task_command.py:416} INFO - Running <TaskInstance: open_fda.transform scheduled__2023-12-12T00:00:00+00:00 [running]> on host e3645a97e7b5
[2023-12-14T10:55:47.010+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_fda' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-12T00:00:00+00:00'
[2023-12-14T10:55:47.015+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/etl/transformation.py", line 7, in transform_data
    create_table()
  File "/opt/airflow/dags/db/table_creation.py", line 14, in create_table
    conn = psycopg2.connect(
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5439" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?

[2023-12-14T10:55:47.024+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=open_fda, task_id=transform, execution_date=20231212T000000, start_date=20231214T105546, end_date=20231214T105547
[2023-12-14T10:55:47.030+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 8 for task transform (connection to server on socket "/var/run/postgresql/.s.PGSQL.5439" failed: No such file or directory
	Is the server running locally and accepting connections on that socket?
; 108)
[2023-12-14T10:55:47.075+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T10:55:47.092+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-14T22:36:44.675+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-14T22:36:44.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: open_fda.transform scheduled__2023-12-12T00:00:00+00:00 [queued]>
[2023-12-14T22:36:44.700+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2023-12-14T22:36:44.719+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): transform> on 2023-12-12 00:00:00+00:00
[2023-12-14T22:36:44.728+0000] {standard_task_runner.py:57} INFO - Started process 96 to run task
[2023-12-14T22:36:44.732+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'open_fda', 'transform', 'scheduled__2023-12-12T00:00:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/outcome_dag.py', '--cfg-path', '/tmp/tmpttmsdy01']
[2023-12-14T22:36:44.733+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask transform
[2023-12-14T22:36:44.791+0000] {task_command.py:416} INFO - Running <TaskInstance: open_fda.transform scheduled__2023-12-12T00:00:00+00:00 [running]> on host 3a11139d188c
[2023-12-14T22:36:44.925+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='open_fda' AIRFLOW_CTX_TASK_ID='transform' AIRFLOW_CTX_EXECUTION_DATE='2023-12-12T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-12T00:00:00+00:00'
[2023-12-14T22:36:45.917+0000] {logging_mixin.py:154} INFO - Tables have been created
[2023-12-14T22:36:46.035+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/context.py:314: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(k, replacements))

[2023-12-14T22:36:49.423+0000] {warnings.py:109} WARNING - /opt/***/dags/etl/transformation.py:61: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_values[f'{col}_id'] = range(max_id + 1, max_id + 1 + len(new_values))

[2023-12-14T22:36:52.487+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-12_recall_fct.csv'.
[2023-12-14T22:36:55.631+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-12_firm_dim.csv'.
[2023-12-14T22:36:56.250+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-12_status_dim.csv'.
[2023-12-14T22:36:56.803+0000] {logging_mixin.py:154} INFO - File uploaded successfully to 'dsc-bucket-1/transformed/2023-12-12_cause_dim.csv'.
[2023-12-14T22:36:56.809+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-12-14T22:36:56.836+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=open_fda, task_id=transform, execution_date=20231212T000000, start_date=20231214T223644, end_date=20231214T223656
[2023-12-14T22:36:56.898+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-12-14T22:36:56.920+0000] {taskinstance.py:2778} INFO - 1 downstream tasks scheduled from follow-on schedule check
